project:
  type: website

website:
  title: "Shiny เบื้องต้น"
  navbar:
    left:
      - href: 01-workshop.qmd
        text: หน้าแรก
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/slphyx
        text: Slphyx Twitter
      - icon: github
        href: https://github.com/slphyx
        text: Slphyx GitHub
  sidebar:
    - id: get-start
      title: "Get Start"
      style: floating
      collapse-level: 2
      alignment: left
      contents: 
        - 01-workshop.qmd
        - 02-introduction.qmd
        - 03-user-interface.qmd
        - 04-server-reactive-programming.qmd
        - 05-visualization.qmd
        - 06-mapping.qmd
        - 07-theming.qmd
        - 08-deployment.qmd
        - 09-guerry-app-all-code.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

